GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/669f082f976be703c9f87927

###
DELETE http://localhost:3001/api/persons/66ac215e47fd378f8dc4066e

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Aylin Siete",
  "number": "03-345"
}

###
PUT http://localhost:3001/api/persons/66a2937546ae1621ac98c507
Content-Type: application/json

{
  "name": "Ryan Dahl",
  "number": "51-987-345-322"
}